### ISSUE TITLE
CMD Include EDB Parser switch

### ISSUE THREAD

**Issue by stark4n6** [thumbcacheviewer/thumbcacheviewer#9]
Any way to include a switch for the commandline to also add the EDB mapping as well?

**Comment by thumbcacheviewer** [comment]
Would that be for the command-line version of the program (thumbcache_viewer_cmd.exe) or the GUI version (thumbcache_viewer.exe)?

**Comment by stark4n6** [comment]
For CMD, for automating output

**Comment by thumbcacheviewer** [comment]
I'll have something working by the weekend.

**Comment by stark4n6** [comment]
Awesome, let me know if you need me to test anything, thanks so much

**Comment by thumbcacheviewer** [comment]
A new version is up: https://github.com/thumbcacheviewer/thumbcacheviewer/releases/download/v1.0.1.9/thumbcache_viewer_cmd.zip

I added the -e switch to map Windows.edb databases. The mapped information is shown in the console window and HTML reports if those are set for output. I didn't include that information in the CSV reports.

Anyway the command-line arguments would look something like this: `thumbcache_viewer_cmd.exe -e "C:\Test\Windows.edb" "C:\Test\thumbcache_256.db"`

**Comment by stark4n6** [comment]
So this will work on a single file and not a folder correct?

**Comment by thumbcacheviewer** [comment]
The example I gave above will work on a single file. If you'd like to run it on a directory of thumbcache files, then you can do something like this: `thumbcache_viewer_cmd.exe -e "C:\Test\Windows.edb" -d "C:\Test\Thumbcache_Folder"`

I'm going to clean up how the arguments are processed so it's more versatile. The switches will all be the same, but it should handle them out of order and whatnot. I'll have a new version up by the end of the week.

**Comment by stark4n6** [comment]
Ok cool, I'll keep testing

**Comment by thumbcacheviewer** [comment]
New version is up: https://github.com/thumbcacheviewer/thumbcacheviewer/releases/download/v1.0.2.0/thumbcache_viewer_cmd.zip

I did end up adding a switch for individual thumbcache files. You'll have to use -t to open them now.

It's now possible to add as many directories and/or thumbcache files as you'd like. Only one Windows Search edb can be loaded for them though.

Example: `thumbache_viewer_cmd.exe -e "C:\Windows.edb" -t "C:\Test\thumbcache_32.db" -t "C:\Test\thumbcache_256.db" -d "C:\More\Databases" -d "E:\External\Folder"`

The arguments can be in any order too.

**Comment by Podbrushkin** [comment]
I suppose windows search database is needed to see filepaths for thumbs. Unfortunately, there is no `C:\ProgramData\Microsoft\Search\Data\Applications\Windows\windows.edb` file, only `windows.db`. 
Maybe that's because I use Windows 11. When I run  `thumbcache_viewer_cmd.exe -t "C:\Users\user\Desktop\thumbcache_96.db" -e Windows.db -n -o . -w` there is no filepaths in resulting html report. What can be the case? Different Windows search database or am I doing something wrong?

**Comment by thumbcacheviewer** [comment]
It's most likely a different version of database. I'll have to find a copy of Windows 11 to test things.

**Comment by markmckinnon** [comment]
In Windows 11 the windows search database utilizes SQLite as its database not Esedb.

**Comment by thumbcacheviewer** [comment]
Yeah I just installed Windows 11 on a virtual machine and figured it out. Adding support for it shouldn't be difficult, but it may take me a while to get to it.

**Comment by stark4n6** [comment]
Yeah, Windows 11 broke things apart, here's a good read on it https://www.aon.com/cyber-solutions/aon_cyber_labs/windows-search-index-the-forensic-artifact-youve-been-searching-for/

**Comment by thumbcacheviewer** [comment]
A new version is up for both the GUI and command-line.

I also compiled a 64-bit version for the command-line.

32-bit: https://github.com/thumbcacheviewer/thumbcacheviewer/releases/download/v1.0.2.1/thumbcache_viewer_cmd_32.zip
64-bit: https://github.com/thumbcacheviewer/thumbcacheviewer/releases/download/v1.0.2.1/thumbcache_viewer_cmd_64.zip

In order to read the Windows.db (SQLite) files you'll need to have the sqlite3.dll in the same folder as the program or in the System32 folder. You can download it under the "Precompiled Binaries for Windows" section from the SQLite website: https://www.sqlite.org/download.html

If you're running the program from within Windows 11, then you won't need sqlite3.dll. There's a native library called SearchIndexerCore.dll that has the same necessary functions. It's not documented and so I've coded it to be a fallback if sqlite3.dll is not found.

**Comment by stark4n6** [comment]
I forgot about this one but I think we can close it out, thanks for the updates!
